using System;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using EiTRVO.ProEngine.Helpers;
using EiTRVO.ProEngine.Models;
using EiTRVO.ProEngine.Orchestrators;

namespace EiTRVO.ProEngine.ViewModels;

public partial class HomeViewModel : BaseViewModel
{
    private readonly LaunchOrchestrator _launchOrchestrator;
    private readonly INotificationService _notificationService;
    private readonly AccountManager _accountManager;
    private readonly InstanceManager _instanceManager;
    private readonly IGameFolderService _gameFolder;

    // === Observable Properties (generated by CommunityToolkit.Mvvm) ===

    [ObservableProperty]
    private GameInstance? _selectedInstance;

    [ObservableProperty]
    private Account? _selectedAccount;

    [ObservableProperty]
    private int _memory = Helpers.SystemMemoryInfo.RecommendedDefaultMemoryMB;

    [ObservableProperty]
    private string? _selectedResolution;

    /// <summary>调试模式：开启时跳过 Java 版本兼容性检查。</summary>
    [ObservableProperty]
    private bool _debugMode;

    [ObservableProperty]
    private string _customWidth = "";

    [ObservableProperty]
    private string _customHeight = "";

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsNotLaunching))]
    [NotifyPropertyChangedFor(nameof(IsGameRunning))]
    private bool _isLaunching;

    /// <summary>标记用户是否通过强制关闭按钮主动终止游戏。</summary>
    private bool _forceClosed;

    /// <summary>缓存上次启动参数，供快速启动使用。</summary>
    private GameInstance? _lastInstance;
    private Account? _lastAccount;
    private JavaInfo? _lastJava;
    private int _lastMemory;
    private string? _lastWidth;
    private string? _lastHeight;

    /// <summary>游戏是否正在运行（用于启用强制关闭按钮）。</summary>
    public bool IsGameRunning => _isLaunching || _launchOrchestrator.IsGameRunning;

    [ObservableProperty]
    private JavaInfo? _selectedJava;

    /// <summary>Set by LaunchCommand on failure so the View can show the failure dialog.</summary>
    [ObservableProperty]
    private string? _lastErrorMessage;

    /// <summary>Set by LaunchCommand on failure so the View can show the diagnostic log path.</summary>
    [ObservableProperty]
    private string? _lastErrorLogPath;

    /// <summary>上次启动的实例名称，供快速启动按钮显示。</summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasLastLaunch))]
    private string? _lastLaunchedInstanceName;

    /// <summary>是否有可用的上次启动记录。</summary>
    public bool HasLastLaunch => !string.IsNullOrEmpty(LastLaunchedInstanceName);

    // === Events for View interaction ===

    /// <summary>Raised when a launch attempt fails, so the View can show the failure dialog.</summary>
    public event Action<string, string?>? LaunchFailed;

    /// <summary>Raised when a launch attempt starts. Parameter is the instance name.</summary>
    public event Action<string>? LaunchStarted;

    /// <summary>存档锁解锁回调 — 由 MainWindow 注入，在启动时显示 UnlockPanel。</summary>
    public Func<string[], System.Threading.CancellationToken, System.Threading.Tasks.Task<UnlockResult>>? SaveUnlockHandler { get; set; }

    /// <summary>正版提醒回调 — 由 MainWindow 注入，无正版账号时弹窗提醒购买。</summary>
    public Func<System.Threading.Tasks.Task>? BuyMinecraftReminder { get; set; }

    /// <summary>Java 兼容性检查回调 — 由 MainWindow 注入，Java 版本不满足 MC 要求时弹窗。</summary>
    public Func<JavaInfo, GameInstance, System.Threading.Tasks.Task<JavaInfo?>>? JavaCompatibilityHandler { get; set; }

    // === Collections (shared references from managers) ===

    public ObservableCollection<GameInstance> LocalInstances => _instanceManager.Instances;
    public ObservableCollection<Account> Accounts => _accountManager.Accounts;
    public ObservableCollection<JavaInfo> JavaInfos { get; } = new();

    // === Computed ===
    public bool IsCustomResolution => SelectedResolution == "自定义";
    public bool IsNotLaunching => !IsLaunching;

    public HomeViewModel(
        LaunchOrchestrator launchOrchestrator,
        INotificationService notificationService,
        AccountManager accountManager,
        InstanceManager instanceManager,
        IGameFolderService gameFolder)
    {
        _launchOrchestrator = launchOrchestrator;
        _notificationService = notificationService;
        _accountManager = accountManager;
        _instanceManager = instanceManager;
        _gameFolder = gameFolder;
    }

    /// <summary>
    /// 启动游戏。自动判断离线/微软/Yggdrasil 模式。
    /// 使用当前选中的实例和账号。
    /// </summary>
    [RelayCommand]
    private async Task LaunchAsync()
    {
        _forceClosed = false;

        var instance = SelectedInstance;
        var account = SelectedAccount;
        var javaInfo = SelectedJava;
        int memory = Memory;

        if (!ValidateLaunchInputs(instance, account, javaInfo, memory, out string? width, out string? height))
            return;

        await LaunchCoreAsync(instance!, account!, javaInfo!, memory, width, height);
    }

    /// <summary>使用上次启动的参数快速启动。</summary>
    [RelayCommand]
    private async Task QuickLaunchAsync()
    {
        if (!HasLastLaunch)
        {
            _notificationService.Show("请先手动启动一次游戏。", NotificationType.Info);
            return;
        }

        _forceClosed = false;

        if (_launchOrchestrator.IsGameRunning)
        {
            _notificationService.Show("游戏已在运行中。", NotificationType.Warning);
            return;
        }

        await LaunchCoreAsync(_lastInstance!, _lastAccount!, _lastJava!, _lastMemory,
            _lastWidth, _lastHeight);
    }

    /// <summary>验证启动输入参数，解析分辨率。返回 false 表示验证失败。</summary>
    private bool ValidateLaunchInputs(GameInstance? instance, Account? account, JavaInfo? java,
        int memory, out string? width, out string? height)
    {
        width = null; height = null;

        if (_launchOrchestrator.IsGameRunning)
        {
            _notificationService.Show("游戏已在运行中。", NotificationType.Warning);
            return false;
        }
        if (instance == null)
        {
            _notificationService.Show("请先选择要启动的实例。", NotificationType.Warning);
            return false;
        }
        if (account == null)
        {
            _notificationService.Show("请先选择账号。", NotificationType.Warning);
            return false;
        }
        if (java == null)
        {
            _notificationService.Show("请先选择 Java 运行环境。", NotificationType.Warning);
            return false;
        }
        if (memory > 32768)
        {
            _notificationService.Show("分配内存不能超过 32768 MB。", NotificationType.Warning);
            return false;
        }

        if (SelectedResolution == "自定义")
        {
            width = CustomWidth.Trim();
            height = CustomHeight.Trim();
            if (!int.TryParse(width, out _) || !int.TryParse(height, out _))
            {
                _notificationService.Show("分辨率须为有效整数（如 1920 和 1080）。", NotificationType.Warning);
                return false;
            }
        }
        else if (SelectedResolution != null && SelectedResolution.Contains("x"))
        {
            var parts = SelectedResolution.Split('x');
            if (parts.Length == 2) { width = parts[0].Trim(); height = parts[1].Trim(); }
        }

        return true;
    }

    /// <summary>核心启动逻辑。LaunchAsync 和 QuickLaunchAsync 共用。</summary>
    private async Task LaunchCoreAsync(GameInstance instance, Account account, JavaInfo javaInfo,
        int memory, string? width, string? height)
    {
        // 保存本次启动参数，供快速启动复用
        _lastInstance = instance;
        _lastAccount = account;
        _lastJava = javaInfo;
        _lastMemory = memory;
        _lastWidth = width;
        _lastHeight = height;
        LastLaunchedInstanceName = instance.Name;

        // === Java 版本兼容性检查（SaveLock 解密前，调试模式下跳过） ===
        if (!_debugMode)
        {
            int requiredJava = PlatformHelper.GetMinecraftRequiredJavaVersion(instance.BaseVersion);
            if (javaInfo.MajorVersion < requiredJava)
            {
                if (JavaCompatibilityHandler != null)
                {
                    var resolved = await JavaCompatibilityHandler(javaInfo, instance);
                    if (resolved == null)
                        return; // 用户取消或无可用 Java
                    javaInfo = resolved;
                    // 同步更新当前选中（普通启动）和快速启动缓存
                    SelectedJava = javaInfo;
                    _lastJava = javaInfo;
                }
            }
        }

        // 持久化快速启动参数（兼容性检查之后，确保 Java 已是最新）
        SaveLastLaunch();

        // 注入存档锁解锁回调
        _launchOrchestrator.UnlockHandler = SaveUnlockHandler;

        LaunchStarted?.Invoke(instance.Name);

        IsLaunching = true;

        try
        {
            LaunchResult result;
            switch (account.Type)
            {
                case AccountType.Microsoft:
                    _notificationService.Show($"正在使用微软账号 {account.Username} 启动 {instance.Name}...", NotificationType.Info);
                    result = await _launchOrchestrator.LaunchWithMicrosoftAsync(instance, account, memory, width, height, javaInfo);
                    break;

                case AccountType.Yggdrasil:
                    _notificationService.Show($"正在使用 {account.ServerDisplayName} {account.Username} 启动 {instance.Name}...", NotificationType.Info);
                    await RemindBuyMinecraftIfNeededAsync();
                    result = await _launchOrchestrator.LaunchWithYggdrasilAsync(instance, account, memory, width, height, javaInfo);
                    break;

                case AccountType.Offline:
                    _notificationService.Show($"正在启动 {instance.Name} ({instance.VersionId})...", NotificationType.Info);
                    await RemindBuyMinecraftIfNeededAsync();
                    result = await _launchOrchestrator.LaunchOfflineAsync(instance, account.Username, memory, width, height, javaInfo);
                    break;

                default:
                    _notificationService.Show("不支持的账号类型。", NotificationType.Warning);
                    return;
            }

            if (!_forceClosed)
                HandleLaunchResult(instance.Name, result);
        }
        catch (Exception ex)
        {
            // 用户主动强制关闭时不弹出错误对话框
            if (_forceClosed) return;

            LastErrorMessage = ex.Message;
            LastErrorLogPath = null;
        }
        finally
        {
            IsLaunching = false;
        }
    }

    /// <summary>将上次启动参数 DPAPI 加密后持久化到磁盘。</summary>
    private void SaveLastLaunch()
    {
        try
        {
            var data = new LastLaunchData
            {
                InstanceName = _lastInstance?.Name,
                AccountUuid = _lastAccount?.UUID,
                JavaPath = _lastJava?.Path,
                Memory = _lastMemory,
                Width = _lastWidth,
                Height = _lastHeight
            };
            string json = JsonSerializer.Serialize(data);
            byte[] plaintext = Encoding.UTF8.GetBytes(json);
            byte[] encrypted = ProtectedData.Protect(plaintext, null, DataProtectionScope.CurrentUser);
            File.WriteAllBytes(_gameFolder.LastLaunchFile, encrypted);
        }
        catch { /* best-effort save */ }
    }

    /// <summary>从磁盘加载上次启动参数（DPAPI 解密）。应在所有数据加载完毕后调用。</summary>
    public async Task LoadLastLaunchAsync()
    {
        try
        {
            string path = _gameFolder.LastLaunchFile;
            if (!File.Exists(path)) return;

            byte[] encrypted = File.ReadAllBytes(path);
            byte[] plaintext = ProtectedData.Unprotect(encrypted, null, DataProtectionScope.CurrentUser);
            string json = Encoding.UTF8.GetString(plaintext);
            var data = JsonSerializer.Deserialize<LastLaunchData>(json);
            if (data == null) return;

            if (!string.IsNullOrEmpty(data.InstanceName))
                _lastInstance = _instanceManager.Instances.FirstOrDefault(i => i.Name == data.InstanceName);
            if (!string.IsNullOrEmpty(data.AccountUuid))
                _lastAccount = _accountManager.Accounts.FirstOrDefault(a => a.UUID == data.AccountUuid);
            if (!string.IsNullOrEmpty(data.JavaPath))
            {
                _lastJava = JavaInfos.FirstOrDefault(j => j.Path == data.JavaPath);
                if (_lastJava == null)
                {
                    // 与设置页自选 Java 相同的校验：运行 java -version
                    var versionInfo = await JavaDetectionService.GetJavaVersionInfoAsync(data.JavaPath);
                    if (versionInfo != null)
                    {
                        _lastJava = new JavaInfo
                        {
                            Path = data.JavaPath,
                            Version = versionInfo.Value.full,
                            ShortVersion = versionInfo.Value.shortVer,
                            MajorVersion = versionInfo.Value.major
                        };
                    }
                    else
                    {
                        LaunchFailed?.Invoke(
                            $"快速启动：上次使用的 Java 运行时无效或已被篡改。\n路径：{data.JavaPath}",
                            null);
                    }
                }
            }
            _lastMemory = data.Memory > 0 ? data.Memory : 2048;
            _lastWidth = data.Width;
            _lastHeight = data.Height;

            if (_lastInstance != null)
                LastLaunchedInstanceName = _lastInstance.Name;
        }
        catch { /* silent — file missing or corrupt */ }
    }

    private void HandleLaunchResult(string instanceName, LaunchResult result)
    {
        if (result.Success)
        {
            _notificationService.Show($"游戏 {instanceName} 已退出。", NotificationType.Info);
        }
        else
        {
            LastErrorMessage = result.ErrorMessage ?? "未知错误";
            LastErrorLogPath = result.DiagnosticLogPath;
            LaunchFailed?.Invoke(LastErrorMessage!, LastErrorLogPath);
        }
    }

    /// <summary>强制关闭正在运行的游戏进程。</summary>
    [RelayCommand]
    private void KillGame()
    {
        if (!_launchOrchestrator.IsGameRunning && !_isLaunching)
        {
            _notificationService.Show("当前没有正在运行的游戏。", NotificationType.Info);
            return;
        }

        _forceClosed = true;
        try
        {
            _launchOrchestrator.KillGame();
            _notificationService.Show("游戏进程已强制关闭。", NotificationType.Warning);
        }
        catch (Exception ex)
        {
            _notificationService.Show($"关闭失败：{ex.Message}", NotificationType.Error);
        }
    }

    /// <summary>若无已登录的微软账号，弹窗提醒玩家购买正版。</summary>
    private async Task RemindBuyMinecraftIfNeededAsync()
    {
        bool hasMicrosoftAccount = _accountManager.Accounts.Any(a => a.Type == AccountType.Microsoft);
        if (!hasMicrosoftAccount && BuyMinecraftReminder != null)
        {
            await BuyMinecraftReminder();
        }
    }

    /// <summary>持久化的快速启动参数（仅关键标识字段）。</summary>
    private class LastLaunchData
    {
        public string? InstanceName { get; set; }
        public string? AccountUuid { get; set; }
        public string? JavaPath { get; set; }
        public int Memory { get; set; }
        public string? Width { get; set; }
        public string? Height { get; set; }
    }
}
