using System;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using EiTRVO.ProEngine.Helpers;
using EiTRVO.ProEngine.Models;
using EiTRVO.ProEngine.Orchestrators;

namespace EiTRVO.ProEngine.ViewModels;

public partial class HomeViewModel : BaseViewModel
{
    private readonly LaunchOrchestrator _launchOrchestrator;
    private readonly INotificationService _notificationService;
    private readonly AccountManager _accountManager;
    private readonly InstanceManager _instanceManager;

    // === Observable Properties (generated by CommunityToolkit.Mvvm) ===

    [ObservableProperty]
    private GameInstance? _selectedInstance;

    [ObservableProperty]
    private string _playerName = "Player";

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsOfflineMode))]
    [NotifyPropertyChangedFor(nameof(IsMicrosoftMode))]
    private bool _useMicrosoft;

    [ObservableProperty]
    private Account? _selectedAccount;

    [ObservableProperty]
    private int _memory = 2048;

    [ObservableProperty]
    private string? _selectedResolution;

    [ObservableProperty]
    private string _customWidth = "";

    [ObservableProperty]
    private string _customHeight = "";

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsNotLaunching))]
    private bool _isLaunching;

    [ObservableProperty]
    private JavaInfo? _selectedJava;

    /// <summary>Set by LaunchCommand on failure so the View can show the failure dialog.</summary>
    [ObservableProperty]
    private string? _lastErrorMessage;

    /// <summary>Set by LaunchCommand on failure so the View can show the diagnostic log path.</summary>
    [ObservableProperty]
    private string? _lastErrorLogPath;

    // === Events for View interaction ===

    /// <summary>Raised when a launch attempt fails, so the View can show the failure dialog.</summary>
    public event Action<string, string?>? LaunchFailed;

    /// <summary>存档锁解锁回调 — 由 MainWindow 注入，在启动时显示 UnlockPanel。</summary>
    public Func<string[], System.Threading.CancellationToken, System.Threading.Tasks.Task<UnlockResult>>? SaveUnlockHandler { get; set; }

    /// <summary>正版提醒回调 — 由 MainWindow 注入，无正版账号时弹窗提醒购买。</summary>
    public Func<System.Threading.Tasks.Task>? BuyMinecraftReminder { get; set; }

    // === Collections (shared references from managers) ===

    public ObservableCollection<GameInstance> LocalInstances => _instanceManager.Instances;
    public ObservableCollection<Account> Accounts => _accountManager.Accounts;
    public ObservableCollection<JavaInfo> JavaInfos { get; } = new();

    // === Computed ===
    public bool IsOfflineMode => !UseMicrosoft;
    public bool IsCustomResolution => SelectedResolution == "自定义";
    public bool IsNotLaunching => !IsLaunching;
    public bool IsMicrosoftMode => UseMicrosoft;

    public HomeViewModel(
        LaunchOrchestrator launchOrchestrator,
        INotificationService notificationService,
        AccountManager accountManager,
        InstanceManager instanceManager)
    {
        _launchOrchestrator = launchOrchestrator;
        _notificationService = notificationService;
        _accountManager = accountManager;
        _instanceManager = instanceManager;
    }

    /// <summary>
    /// 启动游戏。自动判断离线/微软/Yggdrasil 模式。
    /// 所有输入来自 ViewModel 的绑定属性。
    /// </summary>
    [RelayCommand]
    private async Task LaunchAsync()
    {
        if (_launchOrchestrator.IsGameRunning)
        {
            _notificationService.Show(LocalizationHelper.Get("NotificationGameAlreadyRunning"), NotificationType.Warning);
            return;
        }

        if (SelectedInstance == null)
        {
            _notificationService.Show(LocalizationHelper.Get("NotificationSelectInstance"), NotificationType.Warning);
            return;
        }

        if (SelectedJava == null)
        {
            _notificationService.Show(LocalizationHelper.Get("NotificationSelectJava"), NotificationType.Warning);
            return;
        }

        int memory = Memory;
        if (memory > 32768)
        {
            _notificationService.Show("分配内存不能超过 32768 MB。", NotificationType.Warning);
            return;
        }

        // Parse resolution
        string? width = null, height = null;
        if (SelectedResolution == "自定义")
        {
            width = CustomWidth.Trim();
            height = CustomHeight.Trim();
            if (!int.TryParse(width, out _) || !int.TryParse(height, out _))
            {
                _notificationService.Show("分辨率须为有效整数（如 1920 和 1080）。", NotificationType.Warning);
                return;
            }
        }
        else if (SelectedResolution != null && SelectedResolution.Contains("x"))
        {
            var parts = SelectedResolution.Split('x');
            if (parts.Length == 2) { width = parts[0].Trim(); height = parts[1].Trim(); }
        }

        var instance = SelectedInstance;
        var javaInfo = SelectedJava;

        // 注入存档锁解锁回调
        _launchOrchestrator.UnlockHandler = SaveUnlockHandler;

        IsLaunching = true;

        try
        {
            if (UseMicrosoft)
            {
                var account = SelectedAccount;
                if (account == null)
                {
                    _notificationService.Show(LocalizationHelper.Get("NotificationSelectMsAccount"), NotificationType.Warning);
                    return;
                }

                string label = account.Type == AccountType.Yggdrasil ? account.ServerDisplayName : "微软账号";
                _notificationService.Show($"正在使用 {label} {account.Username} 启动 {instance.Name}...", NotificationType.Info);

                LaunchResult result;
                if (account.Type == AccountType.Yggdrasil)
                {
                    await RemindBuyMinecraftIfNeededAsync();
                    result = await _launchOrchestrator.LaunchWithYggdrasilAsync(instance, account, memory, width, height, javaInfo);
                }
                else
                    result = await _launchOrchestrator.LaunchWithMicrosoftAsync(instance, account, memory, width, height, javaInfo);

                HandleLaunchResult(instance.Name, result);
            }
            else
            {
                string playerName = PlayerName.Trim();
                if (string.IsNullOrEmpty(playerName))
                {
                    _notificationService.Show("请输入玩家名。", NotificationType.Warning);
                    return;
                }
                if (!System.Text.RegularExpressions.Regex.IsMatch(playerName, @"^[a-zA-Z0-9_]{3,16}$"))
                {
                    _notificationService.Show("玩家名须为 3-16 位字母、数字或下划线。", NotificationType.Warning);
                    return;
                }

                _notificationService.Show($"正在启动 {instance.Name} ({instance.VersionId})...", NotificationType.Info);
                await RemindBuyMinecraftIfNeededAsync();
                var result = await _launchOrchestrator.LaunchOfflineAsync(instance, playerName, memory, width, height, javaInfo);
                HandleLaunchResult(instance.Name, result);
            }
        }
        catch (Exception ex)
        {
            LastErrorMessage = ex.Message;
            LastErrorLogPath = null;
        }
        finally
        {
            IsLaunching = false;
        }
    }

    private void HandleLaunchResult(string instanceName, LaunchResult result)
    {
        if (result.Success)
        {
            _notificationService.Show($"游戏 {instanceName} 已退出。", NotificationType.Info);
        }
        else
        {
            LastErrorMessage = result.ErrorMessage ?? "未知错误";
            LastErrorLogPath = result.DiagnosticLogPath;
            LaunchFailed?.Invoke(LastErrorMessage!, LastErrorLogPath);
        }
    }

    /// <summary>若无已登录的微软账号，弹窗提醒玩家购买正版。</summary>
    private async Task RemindBuyMinecraftIfNeededAsync()
    {
        bool hasMicrosoftAccount = _accountManager.Accounts.Any(a => a.Type == AccountType.Microsoft);
        if (!hasMicrosoftAccount && BuyMinecraftReminder != null)
        {
            await BuyMinecraftReminder();
        }
    }
}
